export const INDIAN_CITIES = [
  // GUJARAT (Adding many more for user test)
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Surat", state: "Gujarat" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Bhavnagar", state: "Gujarat" },
  { city: "Jamnagar", state: "Gujarat" },
  { city: "Junagadh", state: "Gujarat" },
  { city: "Gandhinagar", state: "Gujarat" },
  { city: "Nadiad", state: "Gujarat" },
  { city: "Morbi", state: "Gujarat" },
  { city: "Surendranagar", state: "Gujarat" },
  { city: "Gandhidham", state: "Gujarat" },
  { city: "Veraval", state: "Gujarat" },
  { city: "Navsari", state: "Gujarat" },
  { city: "Bharuch", state: "Gujarat" },
  { city: "Anand", state: "Gujarat" },
  { city: "Porbandar", state: "Gujarat" },
  { city: "Godhra", state: "Gujarat" },
  { city: "Vapi", state: "Gujarat" },
  { city: "Dahod", state: "Gujarat" },
  { city: "Amreli", state: "Gujarat" },
  { city: "Patan", state: "Gujarat" },
  { city: "Jetpur", state: "Gujarat" },
  { city: "Palanpur", state: "Gujarat" },
  { city: "Kalol", state: "Gujarat" },
  { city: "Mehsana", state: "Gujarat" },
  { city: "Botad", state: "Gujarat" },
  { city: "Valsad", state: "Gujarat" },
  { city: "Gondal", state: "Gujarat" },
  { city: "Deesa", state: "Gujarat" },
  { city: "Visnagar", state: "Gujarat" },
  { city: "Anjar", state: "Gujarat" },
  { city: "Bhuj", state: "Gujarat" },
  { city: "Viramgam", state: "Gujarat" },
  { city: "Mundu", state: "Gujarat" },
  { city: "Keshod", state: "Gujarat" },
  { city: "Modasa", state: "Gujarat" },
  { city: "Savarkundla", state: "Gujarat" },
  { city: "Kadi", state: "Gujarat" },
  { city: "Himatnagar", state: "Gujarat" },
  { city: "Mahuva", state: "Gujarat" },
  { city: "Khambhat", state: "Gujarat" },
  { city: "Dhoraji", state: "Gujarat" },
  { city: "Tharad", state: "Gujarat" },
  { city: "Vyara", state: "Gujarat" },

  // MAHARASHTRA
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Thane", state: "Maharashtra" },
  { city: "Pimpri-Chinchwad", state: "Maharashtra" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Kalyan-Dombivli", state: "Maharashtra" },
  { city: "Vasai-Virar", state: "Maharashtra" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Navi Mumbai", state: "Maharashtra" },
  { city: "Solapur", state: "Maharashtra" },
  { city: "Mira-Bhayandar", state: "Maharashtra" },
  { city: "Bhiwandi", state: "Maharashtra" },
  { city: "Amravati", state: "Maharashtra" },
  { city: "Nanded", state: "Maharashtra" },
  { city: "Kolhapur", state: "Maharashtra" },
  { city: "Akola", state: "Maharashtra" },
  { city: "Ulhasnagar", state: "Maharashtra" },
  { city: "Sangli-Miraj & Kupwad", state: "Maharashtra" },
  { city: "Malegaon", state: "Maharashtra" },
  { city: "Jalgaon", state: "Maharashtra" },
  { city: "Latur", state: "Maharashtra" },
  { city: "Dhule", state: "Maharashtra" },
  { city: "Ahmednagar", state: "Maharashtra" },
  { city: "Chandrapur", state: "Maharashtra" },
  { city: "Parbhani", state: "Maharashtra" },
  { city: "Ichalkaranji", state: "Maharashtra" },
  { city: "Jalna", state: "Maharashtra" },
  { city: "Ambarnath", state: "Maharashtra" },
  { city: "Panvel", state: "Maharashtra" },
  { city: "Badlapur", state: "Maharashtra" },
  { city: "Satara", state: "Maharashtra" },
  { city: "Beed", state: "Maharashtra" },
  { city: "Yavatmal", state: "Maharashtra" },
  { city: "Gondia", state: "Maharashtra" },
  { city: "Solapur", state: "Maharashtra" },

  // RAJASTHAN
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Bikaner", state: "Rajasthan" },
  { city: "Ajmer", state: "Rajasthan" },
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Bhilwara", state: "Rajasthan" },
  { city: "Alwar", state: "Rajasthan" },
  { city: "Bharatpur", state: "Rajasthan" },
  { city: "Sikar", state: "Rajasthan" },
  { city: "Pali", state: "Rajasthan" },
  { city: "Sri Ganganagar", state: "Rajasthan" },
  { city: "Beawar", state: "Rajasthan" },
  { city: "Tonk", state: "Rajasthan" },
  { city: "Hanumangarh", state: "Rajasthan" },
  { city: "Churu", state: "Rajasthan" },
  { city: "Jhunjhunu", state: "Rajasthan" },
  { city: "Kishangarh", state: "Rajasthan" },
  { city: "Nagaur", state: "Rajasthan" },

  // MADHYA PRADESH
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Ujjain", state: "Madhya Pradesh" },
  { city: "Sagar", state: "Madhya Pradesh" },
  { city: "Dewas", state: "Madhya Pradesh" },
  { city: "Satna", state: "Madhya Pradesh" },
  { city: "Ratlam", state: "Madhya Pradesh" },
  { city: "Rewa", state: "Madhya Pradesh" },
  { city: "Murwara", state: "Madhya Pradesh" },
  { city: "Singrauli", state: "Madhya Pradesh" },
  { city: "Burhanpur", state: "Madhya Pradesh" },
  { city: "Khandwa", state: "Madhya Pradesh" },
  { city: "Bhind", state: "Madhya Pradesh" },
  { city: "Chhindwara", state: "Madhya Pradesh" },
  { city: "Guna", state: "Madhya Pradesh" },
  { city: "Shivpuri", state: "Madhya Pradesh" },
  { city: "Vidisha", state: "Madhya Pradesh" },

  // UTTAR PRADESH
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Allahabad", state: "Uttar Pradesh" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Moradabad", state: "Uttar Pradesh" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Gorakhpur", state: "Uttar Pradesh" },
  { city: "Noida", state: "Uttar Pradesh" },
  { city: "Firozabad", state: "Uttar Pradesh" },
  { city: "Jhansi", state: "Uttar Pradesh" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Mathura", state: "Uttar Pradesh" },
  { city: "Rampur", state: "Uttar Pradesh" },
  { city: "Shahjahanpur", state: "Uttar Pradesh" },
  { city: "Farrukhabad", state: "Uttar Pradesh" },
  { city: "Hapur", state: "Uttar Pradesh" },
  { city: "Maunath Bhanjan", state: "Uttar Pradesh" },
  { city: "Etawah", state: "Uttar Pradesh" },
  { city: "Mirzapur", state: "Uttar Pradesh" },
  { city: "Bulandshahr", state: "Uttar Pradesh" },
  { city: "Sambhal", state: "Uttar Pradesh" },
  { city: "Amroha", state: "Uttar Pradesh" },
  { city: "Hardoi", state: "Uttar Pradesh" },
  { city: "Fatehpur", state: "Uttar Pradesh" },
  { city: "Raebareli", state: "Uttar Pradesh" },

  // DELHI
  { city: "Delhi", state: "Delhi" },
  { city: "New Delhi", state: "Delhi" },

  // KARNATAKA
  { city: "Bangalore", state: "Karnataka" },
  { city: "Hubli-Dharwad", state: "Karnataka" },
  { city: "Mysore", state: "Karnataka" },
  { city: "Gulbarga", state: "Karnataka" },
  { city: "Belgaum", state: "Karnataka" },
  { city: "Mangalore", state: "Karnataka" },
  { city: "Davanagere", state: "Karnataka" },
  { city: "Bellary", state: "Karnataka" },
  { city: "Bijapur", state: "Karnataka" },
  { city: "Shimoga", state: "Karnataka" },
  { city: "Tumkur", state: "Karnataka" },
  { city: "Raichur", state: "Karnataka" },
  { city: "Bidar", state: "Karnataka" },
  { city: "Hospet", state: "Karnataka" },
  { city: "Hassan", state: "Karnataka" },

  // TAMIL NADU
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Tiruchirappalli", state: "Tamil Nadu" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Tirunelveli", state: "Tamil Nadu" },
  { city: "Tiruppur", state: "Tamil Nadu" },
  { city: "Ambattur", state: "Tamil Nadu" },
  { city: "Avadi", state: "Tamil Nadu" },
  { city: "Tiruvottiyur", state: "Tamil Nadu" },
  { city: "Thoothukudi", state: "Tamil Nadu" },
  { city: "Nagercoil", state: "Tamil Nadu" },
  { city: "Thanjavur", state: "Tamil Nadu" },
  { city: "Pallavaram", state: "Tamil Nadu" },
  { city: "Dindigul", state: "Tamil Nadu" },
  { city: "Vellore", state: "Tamil Nadu" },

  // WEST BENGAL
  { city: "Kolkata", state: "West Bengal" },
  { city: "Howrah", state: "West Bengal" },
  { city: "Durgapur", state: "West Bengal" },
  { city: "Asansol", state: "West Bengal" },
  { city: "Siliguri", state: "West Bengal" },
  { city: "Maheshtala", state: "West Bengal" },
  { city: "Rajpur Sonarpur", state: "West Bengal" },
  { city: "South Dum Dum", state: "West Bengal" },
  { city: "Gopalpur", state: "West Bengal" },
  { city: "Bhatpara", state: "West Bengal" },
  { city: "Panihati", state: "West Bengal" },
  { city: "Kamarhati", state: "West Bengal" },
  { city: "Bardhaman", state: "West Bengal" },
  { city: "Kulti", state: "West Bengal" },
  { city: "Bally", state: "West Bengal" },
  { city: "Barasat", state: "West Bengal" },
  { city: "Haldia", state: "West Bengal" },
  { city: "Habra", state: "West Bengal" },
  { city: "Kharagpur", state: "West Bengal" },

  // TELANGANA
  { city: "Hyderabad", state: "Telangana" },
  { city: "Warangal", state: "Telangana" },
  { city: "Nizamabad", state: "Telangana" },
  { city: "Karimnagar", state: "Telangana" },
  { city: "Ramagundam", state: "Telangana" },
  { city: "Khammam", state: "Telangana" },
  { city: "Mahbubnagar", state: "Telangana" },

  // ANDHRA PRADESH
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Guntur", state: "Andhra Pradesh" },
  { city: "Nellore", state: "Andhra Pradesh" },
  { city: "Kurnool", state: "Andhra Pradesh" },
  { city: "Kakinada", state: "Andhra Pradesh" },
  { city: "Rajahmundry", state: "Andhra Pradesh" },
  { city: "Tirupati", state: "Andhra Pradesh" },
  { city: "Anantapur", state: "Andhra Pradesh" },
  { city: "Kadapa", state: "Andhra Pradesh" },
  { city: "Vizianagaram", state: "Andhra Pradesh" },
  { city: "Eluru", state: "Andhra Pradesh" },

  // PUNJAB
  { city: "Ludhiana", state: "Punjab" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Jalandhar", state: "Punjab" },
  { city: "Patiala", state: "Punjab" },
  { city: "Bathinda", state: "Punjab" },
  { city: "Mohali", state: "Punjab" },
  { city: "Hoshiarpur", state: "Punjab" },
  { city: "Pathankot", state: "Punjab" },

  // HARYANA
  { city: "Faridabad", state: "Haryana" },
  { city: "Gurgaon", state: "Haryana" },
  { city: "Rohtak", state: "Haryana" },
  { city: "Hisar", state: "Haryana" },
  { city: "Panipat", state: "Haryana" },
  { city: "Karnal", state: "Haryana" },
  { city: "Sonipat", state: "Haryana" },
  { city: "Ambala", state: "Haryana" },

  // BIHAR
  { city: "Patna", state: "Bihar" },
  { city: "Gaya", state: "Bihar" },
  { city: "Bhagalpur", state: "Bihar" },
  { city: "Muzaffarpur", state: "Bihar" },
  { city: "Purnia", state: "Bihar" },
  { city: "Darbhanga", state: "Bihar" },
  { city: "Arrah", state: "Bihar" },
  { city: "Begusarai", state: "Bihar" },

  // CHHATTISGARH
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Bhilai", state: "Chhattisgarh" },
  { city: "Bilaspur", state: "Chhattisgarh" },
  { city: "Korba", state: "Chhattisgarh" },

  // ODISHA
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Cuttack", state: "Odisha" },
  { city: "Rourkela", state: "Odisha" },
  { city: "Berhampur", state: "Odisha" },

  // KERALA
  { city: "Thiruvananthapuram", state: "Kerala" },
  { city: "Kochi", state: "Kerala" },
  { city: "Kozhikode", state: "Kerala" },
  { city: "Kollam", state: "Kerala" },

  // UTTARAKHAND
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Haridwar", state: "Uttarakhand" },
  { city: "Roorkee", state: "Uttarakhand" },

  // JHARKHAND
  { city: "Jamshedpur", state: "Jharkhand" },
  { city: "Dhanbad", state: "Jharkhand" },
  { city: "Ranchi", state: "Jharkhand" },

  // ASSAM
  { city: "Guwahati", state: "Assam" },
  { city: "Silchar", state: "Assam" },

  // JAMMU AND KASHMIR
  { city: "Srinagar", state: "Jammu and Kashmir" },
  { city: "Jammu", state: "Jammu and Kashmir" },

  // GOA
  { city: "Panaji", state: "Goa" },
  { city: "Margao", state: "Goa" },

  // HIMACHAL PRADESH
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Dharamshala", state: "Himachal Pradesh" },

  // OTHER
  { city: "Chandigarh", state: "Chandigarh" },
  { city: "Puducherry", state: "Puducherry" },
  { city: "Agartala", state: "Tripura" },
  { city: "Aizawl", state: "Mizoram" },
  { city: "Imphal", state: "Manipur" },
  { city: "Shillong", state: "Meghalaya" },
  { city: "Kohima", state: "Nagaland" },
  { city: "Itanagar", state: "Arunachal Pradesh" },
  { city: "Gangtok", state: "Sikkim" }
];
